apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config  # Ensure this matches your Deployment's volume reference
  namespace: todo-app  # e.g., todo-app
data:
  default.conf: |  # Corrected nginx config
    server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;  # Web root for static assets
    index index.html index.htm;

    location / {
      try_files $uri $uri/ /index.html;  # Serves existing files (e.g., /bundle.js) first, falls back to index.html for SPA routes
    }

    location /api/ {
      proxy_pass http://backend-service:3001/api/;  # Updated: Use K8s service name (no namespace in same-ns setups); preserves /api/ prefix
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
    }
    }


